# Generated by Django 6.0.2 on 2026-02-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('student_class', models.CharField(max_length=20)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('passport', models.ImageField(blank=True, null=True, upload_to='passports/')),
            ],
        ),
    ]
