# Generated by Django 6.0.2 on 2026-02-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='passport',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
