# Generated by Django 6.0.2 on 2026-02-28 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='student',
        ),
    ]
